# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-16 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorname', models.CharField(max_length=200)),
                ('doctordegree', models.CharField(max_length=200)),
                ('speciality', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='')),
                ('hospital', models.CharField(max_length=200)),
                ('workingaddress', models.CharField(max_length=250)),
                ('designation', models.CharField(max_length=100)),
                ('contactno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('contact', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
